### ISSUE TITLE
move_base node is not being launched

### ISSUE THREAD

**Issue by git-afsantos** [jcp19/ros_packages#5]
The `move_base` node is not included in the [compact launch file](../blob/master/rwad2/launch/compact_multipurpose_map.launch). You need to add the following include after the AMCL section, as seen in the [AMCL demo](https://github.com/turtlebot/turtlebot_apps/blob/indigo/turtlebot_navigation/launch/amcl_demo.launch) from TurtleBot.

```xml
<!-- Move base -->
<arg name="custom_param_file" default="$(find turtlebot_navigation)/param/$(arg 3d_sensor)_costmap_params.yaml"/>
<include file="$(find turtlebot_navigation)/launch/includes/move_base.launch.xml">
  <arg name="custom_param_file" value="$(arg custom_param_file)"/>
</include>
```

**Comment by jcp19** [comment]
Added to the file
